### ISSUE TITLE
New Major version

### ISSUE THREAD

**Issue by santigimeno** [node-schedule/node-schedule#220]
I open this issue to track the issues, PRs and commits from dev we want in:

- [x] Remove Date  convenience methods (https://github.com/node-schedule/node-schedule/pull/233)
- [ ] Prepare for ES6 (https://github.com/node-schedule/node-schedule/issues/165, https://github.com/node-schedule/node-schedule/commit/97780b128e22451f75eb16d8603ca8da14961f3f and https://github.com/node-schedule/node-schedule/commit/02a188cf80b03c6b3a16ca2b3049aaaa465f1720)
- [ ] Add reschedule method: https://github.com/node-schedule/node-schedule/issues/193 https://github.com/node-schedule/node-schedule/pull/227
- [ ] Remove `execute` method: https://github.com/node-schedule/node-schedule/issues/183
- [x] Don't allow scheduling jobs in the past: (https://github.com/node-schedule/node-schedule/issues/157. Bring back: https://github.com/node-schedule/node-schedule/commit/c2afc663b1b75a32a62b4d61c45990ffa335ed68)
- [x] Documentation / Changes 

What do you think? Anything I'm missing you'd want to add? Anything to remove from the list ?

**Comment by santigimeno** [comment]
https://github.com/node-schedule/node-schedule/issues/157 added

**Comment by tejasmanohar** [comment]
@santigimeno - To clarify, does the check mean we want it or it's already in `master`?

**Comment by santigimeno** [comment]
@tejasmanohar I just checked the items already implemented in some branch (dev mainly)

**Comment by santigimeno** [comment]
As no timezone support is likely to be added soon, I'm going to remove it from the list

**Comment by tejasmanohar** [comment]
`dev` is really out of date

**Comment by santigimeno** [comment]
@tejasmanohar What about just releasing `1.0.0` with the fixes from leap year? We can later on release a `1.1.0` with the `reschedule` functionality from https://github.com/node-schedule/node-schedule/pull/227 as it's almost ready. Then move the rest for a `2.0.0` release. I think we should not be afraid of releasing majors faster :)

**Comment by tejasmanohar** [comment]
yeah that sounds fair, reschedule doesnt break anything either.

**Comment by albertdatui** [comment]
@santigimeno, so after releasing the version 1.0.0, do I need to push new PR for reschedule function for that branch?

**Comment by santigimeno** [comment]
@albertdatui I already committed the `cron-parser` bugfix to master, so yes please, the reschedule PR should be against master. Thanks for the great job

**Comment by santigimeno** [comment]
Versión 1.0.0 released.

**Comment by mj1856** [comment]
Please add a GH release
https://github.com/node-schedule/node-schedule/releases

**Comment by tejasmanohar** [comment]
https://github.com/node-schedule/node-schedule/releases/tag/v1.0.0

**Comment by mj1856** [comment]
Yes, I see it has a tag, but it needs a "release" also, even if it just points at the tag.  Thanks.

**Comment by tejasmanohar** [comment]
@mj1856 https://github.com/node-schedule/node-schedule/releases/tag/v1.0.0

**Comment by tejasmanohar** [comment]
@mj1856 what'd you need it for? just curious.

**Comment by mj1856** [comment]
I see you added it.  thanks.

Mainly for visibility.  Doesn't look good if the "latest version" isn't really the latest version.

Also, some libraries use this GitHub feature to put other downloads and release notes, though that's not really necessary.

It's fine if you don't use this of course, but then all of the existing "releases" should be removed to prevent confusion.

Thanks.
